'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,ChevronDown,ChevronLeft,ChevronRight,Play,Menu,X,Star,Leaf,Sun,Heart,Coffee,MapPin,Wifi,Check,Clock} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {cafe,navigation,products,extraMenu,reviews,money} from './content';

function Brand(){return <a href="#inicio" className="brand" aria-label="Bule Café e Cozinha — início"><img src="/bule-logo.svg" alt="Bule Café e Cozinha"/></a>}
function Label({children}:{children:React.ReactNode}){return <p className="eyebrow">{children}</p>}
function Stars(){return <span className="stars" aria-label="5 estrelas">★★★★★</span>}
export default function Home(){
 const [navOpen,setNavOpen]=useState(false);
 const [selection,setSelection]=useState<string|null>(null);
 const [aboutSlide,setAboutSlide]=useState(0);
 const [videoOpen,setVideoOpen]=useState(false);
 const aboutImages=[{src:'/images/cafe.jpg',alt:'Ambiente acolhedor da cafeteria, com plantas e mesas de madeira'},{src:'/images/latte.jpg',alt:'Café especial servido no Bule'},{src:'/images/breakfast.jpg',alt:'Brunch da casa servido com cuidado'}];
 const heroRef=useRef<HTMLElement>(null);
 const current=products.find(p=>p.id===selection);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
 useEffect(()=>{const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');if(reduced.matches)return;const timer=window.setInterval(()=>setAboutSlide(index=>(index+1)%aboutImages.length),5000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setNavOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 useEffect(()=>{
  const hero=heroRef.current;
  if(!hero)return;
  const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
  const floatingItems=Array.from(hero.querySelectorAll<HTMLElement>('.floating-item'));
  let frame=0;
  const update=()=>{
   frame=0;
   const rect=hero.getBoundingClientRect();
   const progress=reducedMotion.matches?0:Math.min(1,Math.max(0,-rect.top/rect.height));
   hero.style.setProperty('--splash-scale',String(1+progress*3.2));
   hero.style.setProperty('--splash-turn',`${progress*24}deg`);
   hero.style.setProperty('--cup-shift',`${progress*22}px`);
   hero.style.setProperty('--cup-turn',`${progress*-3}deg`);
   const growth=window.innerWidth<=760?.28:.42;
   floatingItems.forEach(item=>item.style.setProperty('--food-scale',String(1+progress*growth)));
  };
  const schedule=()=>{if(!frame)frame=window.requestAnimationFrame(update)};
  const visibility=new IntersectionObserver(([entry])=>{hero.classList.toggle('motion-paused',!entry.isIntersecting)});
  visibility.observe(hero);
  window.addEventListener('scroll',schedule,{passive:true});
  window.addEventListener('resize',schedule);
  reducedMotion.addEventListener('change',schedule);
  update();
  return()=>{window.cancelAnimationFrame(frame);visibility.disconnect();window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule);reducedMotion.removeEventListener('change',schedule)};
 },[]);
 return <>
 <div className="intro-curtain" aria-hidden="true"><span className="intro-brand"><img src="/bule-logo-branco.svg" alt=""/></span><span className="intro-line"/></div>
 <header className="header"><div className="nav-shell"><Brand/><nav className={navOpen?'nav-links open':'nav-links'} id="main-nav" aria-label="Navegação principal">{navigation.map(([label,link])=><a key={link} href={link} onClick={()=>setNavOpen(false)}>{label}</a>)}</nav><a className="button small header-cta" href="#cardapio">Escolha seu café <ArrowUpRight size={14}/></a><button className="menu-toggle" aria-label={navOpen?'Fechar menu':'Abrir menu'} aria-expanded={navOpen} aria-controls="main-nav" onClick={()=>setNavOpen(!navOpen)}>{navOpen?<X/>:<Menu/>}</button></div></header>
 <main id="inicio">
 <section ref={heroRef} className="hero" aria-labelledby="hero-title"><div className="hero-copy"><span className="pill"><Sun size={12}/> Um pouco de sol em cada xícara</span><h1 id="hero-title">Feito de café.<br/><em>E dias bons.</em></h1></div><div className="hero-visual"><div className="hero-glow" aria-hidden="true"/><div className="hero-splash" aria-hidden="true"/><div className="hero-cup"><img className="hero-cup-image" src="/images/hero.webp" alt="Xícara de cappuccino artesanal com latte art" fetchPriority="high"/></div></div><div className="hero-notes"><span>Grãos especiais.<br/>Pequenos rituais.</span><span>Feito com calma.<br/>Servido com carinho.</span></div>{['beans-cluster','croissant','cookie','sandwich','cake','cookie','coffee-glass'].map((image,i)=><div key={i} className={`floating-item food-${i+1}`} aria-hidden="true"><img src={`/images/${image}.webp`} alt="" width="400" height="400" draggable={false}/></div>)}<a className="scroll-cue" href="#sobre">Sinta-se em casa<ChevronDown size={16}/></a></section>
 <section className="stats container" aria-label="Bule em números">{[['4,8 ★','Avaliação dos clientes'],['500+','Bons encontros'],['8h','O dia começa aqui'],['100%','Café de origem brasileira']].map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
 <section id="sobre" className="about container section reveal"><div className="about-photos"><span className="sticker">Seu novo cantinho ↗</span><div className="about-slideshow" aria-label="Fotos do Bule">{aboutImages.map((photo,i)=><img key={photo.src} className={`cafe-photo about-slide ${i===aboutSlide?'active':''}`} src={photo.src} alt={i===aboutSlide?photo.alt:''} aria-hidden={i!==aboutSlide} loading={i===0?'eager':'lazy'}/>)}<div className="about-slide-controls"><button type="button" aria-label="Foto anterior" onClick={()=>setAboutSlide(i=>(i-1+aboutImages.length)%aboutImages.length)}><ChevronLeft size={17}/></button><span aria-live="polite">{String(aboutSlide+1).padStart(2,'0')} / {String(aboutImages.length).padStart(2,'0')}</span><button type="button" aria-label="Próxima foto" onClick={()=>setAboutSlide(i=>(i+1)%aboutImages.length)}><ChevronRight size={17}/></button></div></div><div className="about-detail" aria-label="Marca Bule Café e Cozinha"><img src="/bule-logo-branco.svg" alt=""/></div></div><div className="about-copy"><Label>Prazer, somos o Bule</Label><h2>Mais que café.<br/><em>Um ritual diário.</em></h2><p>Acreditamos nas pequenas pausas. No aroma do café recém-passado, na primeira mordida e nas conversas que fazem a hora passar diferente.</p><p>Uma casa de portas abertas, onde cada xícara tem uma história — e sempre cabe mais alguém.</p><div className="about-actions"><button type="button" className="about-video-button" onClick={()=>setVideoOpen(true)}><span className="play-circle"><Play size={16} fill="currentColor"/></span>Assista à apresentação</button><button type="button" className="about-tour-button" disabled aria-label="Visão 360 graus: em breve">Visão 360° <span>Em breve</span></button></div></div></section>
 <section id="cardapio" className="menu-section"><div className="container"><div className="section-heading reveal"><Label>O cardápio</Label><h2>Os favoritos da casa.</h2><p>Do primeiro gole à última migalha.<br/>Simples, frescos e cheios de sabor.</p></div><div className="product-list">{products.map((p,i)=><article className={`product reveal ${i%2?'reverse':''}`} key={p.id}><button className="product-image" onClick={()=>setSelection(p.id)} aria-label={`Conhecer ${p.name}`}><img src={p.image} alt={p.alt} loading="lazy"/><span className="image-arrow"><ArrowUpRight size={21}/></span></button><div className="product-copy"><div className="product-meta"><span>{p.category}</span><small>{p.size}</small></div><h3>{p.name}</h3><p>{p.description}</p><div className="product-bottom"><span className="price">{money(p.price)}</span><button className="text-link" onClick={()=>setSelection(p.id)}>Conheça <ArrowUpRight size={14}/></button></div></div></article>)}</div><div className="center"><button className="button" onClick={()=>setSelection('all')}>Ver cardápio completo <ArrowRight size={17}/></button></div></div></section>
 <section id="diferenciais" className="benefits container section"><div className="section-heading reveal"><Label>Nosso jeito de fazer</Label><h2>Pequenos detalhes.<br className="mobile-break"/> Muito carinho.</h2></div><div className="circle-garden">{[{icon:Star,label:'4,8 de amor',sub:'Em cada avaliação',className:'rating'},{icon:Leaf,label:'Bem selecionado',sub:'Da origem à xícara',className:'quality'},{icon:Sun,label:'Fresco todo dia',sub:'Feito aqui, para você',className:'fresh'},{icon:Coffee,label:'Seu lugar de pausa',sub:'Entre, fique à vontade',className:'cozy'},{icon:Heart,label:'Gente que acolhe',sub:'Café com um sorriso',className:'friendly'}].map(b=><div className={`benefit-circle reveal ${b.className}`} key={b.label}><b.icon size={25} strokeWidth={1.4}/><h3>{b.label}</h3><span>{b.sub}</span></div>)}</div></section>
 <section id="depoimentos" className="reviews-section"><div className="container"><div className="review-heading reveal"><div><Label>Quem vem, volta</Label><h2>Bom mesmo é ter<br/>com quem <em>compartilhar.</em></h2></div><div className="rating-badge"><strong>4,8</strong><Stars/><span>É bom estar aqui</span></div></div><div className="reviews-grid">{reviews.map(r=><article className="review-card reveal" key={r.name}><Stars/><blockquote>“{r.text}”</blockquote><div className="reviewer"><span className={`avatar ${r.tone}`}>{r.initials}</span><div><strong>{r.name}</strong><span>{r.detail}</span></div><Check size={14}/></div></article>)}</div></div></section>
 <section id="visite" className="visit container section reveal"><div><Label>Vem ficar um pouco</Label><h2>Um cantinho<br/>no seu <em>caminho.</em></h2><div className="contact-detail"><MapPin size={17}/><div><strong>Nos encontre</strong><p>{cafe.address}<br/>{cafe.city}</p></div></div><div className="contact-detail"><Clock size={17}/><div><strong>Tem café quentinho</strong><p>{cafe.hours}<br/>{cafe.weekend}</p></div></div><p className="phone">{cafe.phone}</p><div className="amenities"><span><Wifi size={12}/> Wi-Fi</span><span>Pet friendly</span><span>Opções vegetais</span></div></div><div className="map-wrap" data-map-provider="illustrated"><div className="map" role="img" aria-label="Mapa ilustrativo da localização da Bule"><span className="block park p1"/><span className="block peach p2"/><span className="block peach p3"/><span className="block park p4"/><span className="street horizontal h1"/><span className="street horizontal h2"/><span className="street vertical v1"/><span className="street vertical v2"/><span className="street-name">Rua do Sol</span><span className="map-pin"><Coffee size={25}/><b>Bule Café</b></span><span className="map-caption">Localização ilustrativa</span></div><a href={cafe.mapUrl} target="_blank" rel="noreferrer" className="map-link">Explorar a região <ArrowUpRight size={15}/></a></div></section>
 <section className="final-cta"><div className="container cta-inner reveal"><div className="cta-photo"><img src="/images/latte.jpg" alt="Um café quentinho esperando pela sua próxima pausa" loading="lazy"/><span className="sticker">A gente te espera!</span></div><div className="cta-copy"><Label>Qual é a sua pausa de hoje?</Label><h2>Seu novo<br/><em>café favorito.</em></h2><p>Café bom, comida de verdade e tempo para o que importa. Puxe uma cadeira.</p><div className="cta-buttons"><a href="#visite" className="button brown">Venha nos visitar <ArrowUpRight size={15}/></a><button className="button light" onClick={()=>setSelection('all')}>Ver cardápio</button></div></div></div></section>
 </main><footer><div className="container footer-main"><Brand/><nav aria-label="Links do rodapé">{navigation.filter((_,i)=>i!==2).map(([label,link])=><a href={link} key={link}>{label}</a>)}</nav><span>{cafe.phone}</span></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Bule Café e Cozinha. Feito com calma.</span><span>Site demonstrativo • endereço, preços e avaliações ilustrativos.</span></div></footer>
 <Dialog open={videoOpen} onOpenChange={setVideoOpen}><DialogContent className="video-dialog"><DialogTitle className="video-dialog-title">Um passeio pelo Bule</DialogTitle><DialogDescription className="video-dialog-description">Apresentação ilustrativa com imagens da casa e do cardápio.</DialogDescription>{videoOpen&&<video controls autoPlay playsInline poster="/images/cafe.jpg" aria-label="Vídeo vertical de apresentação do Bule"><source src="/videos/kosmo-apresentacao.mp4" type="video/mp4"/>Seu navegador não reproduz este vídeo.</video>}</DialogContent></Dialog>
 <Dialog open={selection!==null} onOpenChange={open=>{if(!open)setSelection(null)}}><DialogContent className="menu-dialog">{current?<><img src={current.image} alt={current.alt} className="dialog-photo"/><Label>{current.category}</Label><DialogTitle className="dialog-title">{current.name}</DialogTitle><DialogDescription className="dialog-desc">{current.ingredients}</DialogDescription><p className="allergen">{current.note}</p><div className="dialog-bottom"><strong>{money(current.price)}</strong><a href="#visite" className="button brown" onClick={()=>setSelection(null)}>Experimente na casa <ArrowRight size={15}/></a></div></>:<><Label>Feito com carinho</Label><DialogTitle className="dialog-title">Nosso cardápio</DialogTitle><DialogDescription className="dialog-desc">Sua próxima pausa começa aqui. Brunch servido até as 16h.</DialogDescription><div className="full-menu">{[...products,...extraMenu].map(p=><div key={p.name}><span><strong>{p.name}</strong><small>{p.category}</small></span><b>{money(p.price)}</b></div>)}</div><p className="allergen">Consulte nossa equipe sobre ingredientes e restrições alimentares. Valores ilustrativos.</p><a className="button brown" href="#visite" onClick={()=>setSelection(null)}>Visite o Bule <ArrowUpRight size={16}/></a></>}</DialogContent></Dialog>
 </>
}
